"""empty message

Revision ID: 67201d77987c
Revises: 
Create Date: 2019-08-26 18:57:37.412714

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '67201d77987c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('citizen',
    sa.Column('citizen_id', sa.Integer(), nullable=False),
    sa.Column('import_id', sa.Integer(), nullable=False),
    sa.Column('town', sa.Text(), nullable=True),
    sa.Column('street', sa.Text(), nullable=True),
    sa.Column('building', sa.Text(), nullable=True),
    sa.Column('apartment', sa.Integer(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('birth_date', sa.DateTime(), nullable=True),
    sa.Column('gender', sa.Text(), nullable=True),
    sa.Column('relatives', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.PrimaryKeyConstraint('citizen_id', 'import_id')
    )
    op.create_table('imports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('imports')
    op.drop_table('citizen')
    # ### end Alembic commands ###
